name: CI_DEV

on:
  # execute when pull requested
  pull_request:
    branches: 
      - 'dev'

    paths:
      - '.github/workflows/**'
      - 'base/**'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction

      - name: Run the test with pytest
        run: poetry run pytest tests/
        env:
          BASE_USER_ID: ${{ secrets.BASE_USER_ID }}
          BASE_ACCESS_KEY: ${{ secrets.BASE_ACCESS_KEY }}
          BASE_API_ENDPOINT: ${{ secrets.BASE_API_ENDPOINT }}

  fix-format:
    runs-on: ubuntu-latest
    needs: test

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction

      - name: Format Python Source with Black
        run: poetry run black .

      - name: Push to Pull Requested branch
        run: |
          if ! git diff --exit-code --quiet
          then
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions"

            git add .
            git commit -m "[Actions]Fix format with black."
            git push
          fi